# This project uses https://goreleaser.com to handle its releases.
#
# Dry-run:
#   rm -rf dist && goreleaser release --snapshot --skip-publish
before:
  hooks:
    - go mod tidy
builds:
  - id: ecslog
    main: ./cmd/ecslog
    binary: ecslog
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # These mod_timestamp and ldflags are specified for reproducible builds,
    # i.e. no changing temporal info in the built binaries.
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - "-s -w -X main.commit={{.Commit}}"
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
