name: Check

on:
  push:
    branches:
    - main
    paths-ignore:
    - '*.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: install tools
      run: |
        go get -u golang.org/x/lint/golint
        go get -u golang.org/x/tools/cmd/goimports
    - uses: actions/checkout@v2
    - name: vet
      run: go vet ./cmd/... ./internal/...
    - name: golint
      run: golint ./cmd/... ./internal/...
    - name: fmt
      run: find . -name "*.go" | xargs goimports -l ; echo $?
